debug: true

server:
  port: 8981

spring:
  profiles:
    active: local
  aop: 
    proxy-target-class: true

mybatis:
  mapperLocations: classpath:/mapper/**/*.xml
  configuration:
    jdbcTypeForNull: "NULL"
    mapUnderscoreToCamelCase: true
   
 
ustra:
  core:
    process-info:
      default-system-code: BO
  data:
    procedure-manager:
      enabled: true
    datasource:
      separated-mybatis-scan: true
      default-datasource-name: rds1
      datasources:
        rds1:
          url: jdbc:log4jdbc:sqlserver://framework-sqlserver.c0uiyan5ae24.ap-northeast-2.rds.amazonaws.com:1433;databaseName=USTRA_FW_SPL
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: ENC(p6rIPoShJklFLPxHKNJYFLooNCd2xnkayNZ2f+GexyA17qEMS77u8g==)
          password: ENC(ohS/a1/Q/lKriwUq3rqJqht76fQ0Bnge)
          mybatis:
            base-packages: com.gsitm.ustra.java.sample.template #base package는 필수 값
            mapper-locations: classpath*:/mapper/**/*.xml # mapper의 리소스 범위 지정
        rds2:
          url: jdbc:log4jdbc:sqlserver://framework-sqlserver.c0uiyan5ae24.ap-northeast-2.rds.amazonaws.com:1433;databaseName=USTRA_FW_SPL
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: ENC(p6rIPoShJklFLPxHKNJYFLooNCd2xnkayNZ2f+GexyA17qEMS77u8g==)
          password: ENC(ohS/a1/Q/lKriwUq3rqJqht76fQ0Bnge)
          mybatis:
            base-packages: com.gsitm.ustra.java.sample.template
            annotation-class-name: com.gsitm.ustra.java.sample.config.annotations.Rds2Mapper
            mapper-locations: classpath*:/mapper2/**/*.xml
    mybatis:
      excludeMapperLocationPatterns: test.xml
    file:
      enabled: true
    redis:
      cache:
        enabled: true
      connection:
        hostName: localhost
        port: 6379
        password:
  mvc:
    view:
      api-prefix: api
      client-crypto-key: Z3NjLWNyeXB0by1rZXkxMQ==
      type: STATIC_THYEMELEAF
    rest:
      exclude-wrapping-url-patterns: /v2/api-docs,/swagger-resources/**,/swagger-ui.html,/webjars/**
    wrapper:
      exclude-request-url-patterns: /v2/api-docs
      exclude-response-url-patterns: /v2/api-docs
  management:
    bo:
      app:
        use-auth-approval: true
        use-user-approval: true
        password-change-days: 0
        maximum-auth-group-depth: 5
      authentication:
        allow-anoymous-authentication: true
        system-name: management-bo
        system-key: BO
        token-key: acc-token
        refresh-token-key: ref-token
        secret-key: asddflkhjasd
        enable-refresh-token: true
        refresh-valid-seconds: 6000
app:
  redis:
    bypass: false
  mybatis:
    dual-mapper: true